"""add_documento_consentimiento

Revision ID: 2c438ac0f24b
Revises: 4764abe21b8c
Create Date: 2026-09-14 12:47:38.948279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c438ac0f24b'
down_revision = '4764abe21b8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_configuracion_clave', table_name='configuracion')
    op.drop_index('ix_configuracion_id', table_name='configuracion')
    op.drop_table('configuracion')
    op.add_column('pacientes', sa.Column('documento_consentimiento', sa.String(length=500), nullable=True))
    op.alter_column('pacientes', 'dni',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pacientes', 'frecuencia_deporte',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pacientes', 'frecuencia_deporte',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('pacientes', 'dni',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('pacientes', 'documento_consentimiento')
    op.create_table('configuracion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='configuracion_pkey')
    )
    op.create_index('ix_configuracion_id', 'configuracion', ['id'], unique=False)
    op.create_index('ix_configuracion_clave', 'configuracion', ['clave'], unique=True)
    # ### end Alembic commands ###
