"""campos_detalle_antecedentes

Revision ID: 4764abe21b8c
Revises: fb9ba37c99b3
Create Date: 2026-09-12 16:31:43.880978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4764abe21b8c'
down_revision = 'fb9ba37c99b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_configuracion_clave', table_name='configuracion')
    op.drop_index('ix_configuracion_id', table_name='configuracion')
    op.drop_table('configuracion')
    op.add_column('pacientes', sa.Column('diabetes_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('problemas_cardiovasculares_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('problemas_coagulacion_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('enfermedades_reumaticas_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('enfermedades_neurologicas_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('enfermedades_oseas_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('hepatitis_vih_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('embarazada_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('traumatismos_pies_detalle', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('plantillas_previas_detalle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'plantillas_previas_detalle')
    op.drop_column('pacientes', 'traumatismos_pies_detalle')
    op.drop_column('pacientes', 'embarazada_detalle')
    op.drop_column('pacientes', 'hepatitis_vih_detalle')
    op.drop_column('pacientes', 'enfermedades_oseas_detalle')
    op.drop_column('pacientes', 'enfermedades_neurologicas_detalle')
    op.drop_column('pacientes', 'enfermedades_reumaticas_detalle')
    op.drop_column('pacientes', 'problemas_coagulacion_detalle')
    op.drop_column('pacientes', 'problemas_cardiovasculares_detalle')
    op.drop_column('pacientes', 'diabetes_detalle')
    op.create_table('configuracion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='configuracion_pkey')
    )
    op.create_index('ix_configuracion_id', 'configuracion', ['id'], unique=False)
    op.create_index('ix_configuracion_clave', 'configuracion', ['clave'], unique=True)
    # ### end Alembic commands ###
