"""campos_adicionales_paciente

Revision ID: fb9ba37c99b3
Revises: 96c698064c5c
Create Date: 2026-09-12 10:45:04.028113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb9ba37c99b3'
down_revision = '96c698064c5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_configuracion_clave', table_name='configuracion')
    op.drop_index('ix_configuracion_id', table_name='configuracion')
    op.drop_table('configuracion')
    op.add_column('pacientes', sa.Column('profesion', sa.String(length=100), nullable=True))
    op.add_column('pacientes', sa.Column('contacto_emergencia', sa.String(length=200), nullable=True))
    op.add_column('pacientes', sa.Column('telefono_emergencia', sa.String(length=20), nullable=True))
    op.add_column('pacientes', sa.Column('diabetes', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('problemas_cardiovasculares', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('problemas_coagulacion', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('enfermedades_reumaticas', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('enfermedades_neurologicas', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('enfermedades_oseas', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('hepatitis_vih', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('embarazada', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('cirugias_previas', sa.Text(), nullable=True))
    op.add_column('pacientes', sa.Column('traumatismos_pies', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('plantillas_previas', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('deporte', sa.Boolean(), nullable=True))
    op.add_column('pacientes', sa.Column('frecuencia_deporte', sa.String(length=100), nullable=True))
    op.add_column('pacientes', sa.Column('tipo_calzado', sa.String(length=50), nullable=True))
    op.add_column('pacientes', sa.Column('horas_pie_dia', sa.Integer(), nullable=True))
    op.add_column('pacientes', sa.Column('fumador', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'fumador')
    op.drop_column('pacientes', 'horas_pie_dia')
    op.drop_column('pacientes', 'tipo_calzado')
    op.drop_column('pacientes', 'frecuencia_deporte')
    op.drop_column('pacientes', 'deporte')
    op.drop_column('pacientes', 'plantillas_previas')
    op.drop_column('pacientes', 'traumatismos_pies')
    op.drop_column('pacientes', 'cirugias_previas')
    op.drop_column('pacientes', 'embarazada')
    op.drop_column('pacientes', 'hepatitis_vih')
    op.drop_column('pacientes', 'enfermedades_oseas')
    op.drop_column('pacientes', 'enfermedades_neurologicas')
    op.drop_column('pacientes', 'enfermedades_reumaticas')
    op.drop_column('pacientes', 'problemas_coagulacion')
    op.drop_column('pacientes', 'problemas_cardiovasculares')
    op.drop_column('pacientes', 'diabetes')
    op.drop_column('pacientes', 'telefono_emergencia')
    op.drop_column('pacientes', 'contacto_emergencia')
    op.drop_column('pacientes', 'profesion')
    op.create_table('configuracion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='configuracion_pkey')
    )
    op.create_index('ix_configuracion_id', 'configuracion', ['id'], unique=False)
    op.create_index('ix_configuracion_clave', 'configuracion', ['clave'], unique=True)
    # ### end Alembic commands ###
